baseURL: ''
languageCode: zh-CN
title: Yeelight ã® å°å±‹
theme: "PaperMod"
description: "ç§ãŸã¡ã®æœªæ¥ã¯ã¿ã‚“ãªã§ã¤ãã‚‹"


enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableInlineShortcodes: true #å…è®¸å†…è”çŸ­ç 
enableEmoji: true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT: true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
hasCJKLanguage: true

paginate: 10

minify:
  disableXML: true
  minifyOutput: true

permalinks: #æµè§ˆå™¨é“¾æ¥æ˜¾ç¤ºæ–¹å¼
  post: "/:title/"

defaultContentLanguage: zh-cn # æœ€é¡¶éƒ¨é¦–å…ˆå±•ç¤ºçš„è¯­è¨€é¡µé¢
defaultContentLanguageInSubdir: true

menu:
  main:
    - identifier: about
      name: AboutğŸ‘‹
      url: about
      weight: 10
    - identifier: tags
      name: TagsğŸ”–
      url: tags
      weight: 30
    - identifier: categories
      name: CategoriesğŸ“‚
      url: categories
      weight: 40
    - identifier: archives
      name: ArchivesğŸ“¦
      url: archives
      weight: 50
    - identifier: search
      name: SearchğŸ”
      url: search
      weight: 60

# Main interface settings
params:
    env: production
    author: "Yeelight"
    keywords: [blog, page]
    defaultTheme: auto # dark, light
    math: true

    homeInfoParams:
        Title: ç®€å•æ˜¯ç¨³å®šçš„å‰æ( â€¢Ì€ Ï‰ â€¢Ì )âœ§
        Content: ç§ãŸã¡ã®æœªæ¥ã¯ã¿ã‚“ãªã§ã¤ãã‚‹

    socialIcons: # optional
        - name: email
          url: "mailto:yeelight.work@outlook.com"
        - name: "GitHub"
          url: "https://github.com/FeiNiaoBF"
        - name: "YouTube"
          url: "https://www.youtube.com/channel/UCZsE4g_WIh-KRpjCeF4cABA"
        - name: "bilibili"
          url: "https://space.bilibili.com/592367582?spm_id_from=333.1007.0.0"
        - name: "steam"
          url: "https://store.steampowered.com/"
        - name: facebook
          url: "https://www.facebook.com/profile.php?id=100080738746798"
    # editPost:
    #   URL: "https://github.com/FeiNiaoBF/FeiNiaoBF.github.io"
    #   Text: "Suggest Changes" # edit text
    #   appendFilePath: false # to append file path to Edit link

    env: production
    # shared
    ShowShareButtons: true
    # read time settings
    ShowReadingTime: true
    # breadCrumbs: true
    ShowBreadCrumbs: true
    # next page settings
    ShowPostNavLinks: true
    # copy
    ShowCodeCopyButtons: true
    #
    ShowAllPagesInArchive: true
    ShowWordCounts: true
    VisitCount: true
    ShowLastMod: true
    # comment
    comments: false

    enableInlineShortcodes: true

    cover:
      linkFullImages: true

# Search settings
outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary

    fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 1
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

    # twikoo:
      # version: 1.4.11

    assets:
      disableFingerprinting: true
      disableHLJS: false


markup:
  highlight:
    # anchorLineNos: false # åœ¨è¡Œå·ä¸Šé…ç½®é”šç‚¹
    codeFences: true
    guessSyntax: true
    # hl_Lines: ""
    # hl_inline: false
    # lineAnchors: ""
    # lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    # noHl: false
    style: catppuccin-mocha
    # tabWidth: 4
privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true


tableOfContents:
    endLevel: 3
    ordered: true
    startLevel: 1

ShowToc: true

TocOpen: false
